# Generated by Django 4.1.7 on 2023-03-04 19:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=512)),
                ("pan", models.CharField(max_length=20)),
                (
                    "fingerprint",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.upload_path_handler
                    ),
                ),
            ],
        ),
    ]
